linguagem neutra e erros de português apontados por amanda kiyama
Kazuo256/guiadobixo pull request #96
Opened 2019-01-28 15:53 UTC by Pedro9Paulo

2019-01-29 15:47 UTC, Kazuo256 approved these changes

2019-01-29 15:49 UTC, Kazuo256 requested changes
@Pedro9Paulo Por que que esse PR apaga o texto do MaratonUSP?

2019-01-31 12:44 UTC, Pedro9Paulo commented
eu devo ter apagado acidentalmente junto com os .out .aux, mil desculpas pela demora em arrumar isso, já corrigi

2019-01-31 12:52 UTC, Kazuo256 approved these changes

2019-01-31 12:52 UTC, merged